- hosts: all
  become: true
  tasks: 
    # - name: delete old deployment
    #   shell: "kubectl delete -f /home/ubuntu/Deployment.yml --kubeconfig=/home/ubuntu/.kube/config"
    # - name: delete old service
    #   shell: "kubectl delete -f /home/ubuntu/Service.yml --kubeconfig=/home/ubuntu/.kube/config"
     - name: create new deployment
       shell: "kubectl apply -f /home/ubuntu/Deployment.yml --kubeconfig=/home/ubuntu/.kube/config"
     - name: create new service
       shell: "kubectl apply -f /home/ubuntu/Service.yml --kubeconfig=/home/ubuntu/.kube/config"
     - name: add port-forwarding for external access
       shell: "kubectl port-forward --address 0.0.0.0 service/arinx 8080:8080 --kubeconfig=/home/ubuntu/.kube/config"
