kind: Service                             
apiVersion: v1
metadata:
  name: arinx
  labels:
    app: arinx
spec:
  ports:
    - port: 8080                               
      targetPort: 80  
      nodePort: 30000
  selector:
    app: arinx                    
  type: LoadBalancer
